name: 🚀 Deploy
on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses : actions/checkout@v3

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.0.2
        id: app_name
        with:
          file: "fly.toml"
          field: "app"

      - name: 🚀 Deploy Stage
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --remote-only --app ${{ steps.app_name.outputs.value }}-stage"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: 🚀 Deploy Production
        if: ${{ github.ref == 'refs/heads/production' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --remote-only --app ${{ steps.app_name.outputs.value }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}